version: '3'
services:
  web:
    build: .
    container_name: two-api
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - .:/two:cached
    ports:
      - "3005:3000"
    depends_on:
      - mysql
      - mongodb
    tty: true
    stdin_open: true
  mysql:
    container_name: two-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33070:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  mongodb:
    image: mongo:3.6
    container_name: two-mongodb
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root